---
- descriptor: "pip-services:logger:console:default:1.0"
  level: "trace"

- descriptor: "pip-services-tags:persistence:file:default:1.0"
  path: "./data/tags.json"

- descriptor: "pip-services-tags:controller:default:default:1.0"
  options:
    max_tag_count: 100

- descriptor: "pip-services-tags:service:http:default:1.0"
  connection:
    protocol: "http"
    host: "0.0.0.0"
    port: 8080
